### ISSUE TITLE
Verbesserungsvorschlag

### ISSUE THREAD

**Issue by BernhardLinz** [MiRo1310/ioBroker.alexa-shoppinglist#2]
Dank eines Tipps von l**iv-in-sky** bin ich über deinen Adapter gestolpert (in der Diskussion aus seiner HTML-Tabelle eine JSON Version zu machen - was ich gemacht habe).

Nur so mal als Idee:

Deine JSON-Version in 
`alexa-shoppinglist.0.list_activ`

hat ja name, time, id und pos.
**liv-in-sky** baut in seiner HTML-Tabelle einen Button zum löschen ein, ich habe das mal für die JSON-Variante auch so gemacht.
Und zumindest das inventwo-JSON-Tabelle Widget bringt dann einen anklickbaren und funktionierenden Button:

hier die wichtigsten Schnippsel:

**Code des Buttons für den JSON**
`
var symbolLink="❌";                                                                    //  👎  💀 ❌  ⚪  ⚫ ⭕  🔴 🔵
// Nachfolgend der Link den man sich aus der id zusammenbauen könnte für das löschen einer einzelnen Position
var valButton="alexa2.0.Lists.SHOPPING_LIST.items.03ad1ed3-4777-4fa4-a036-3681340be1a1.#delete"
// Der Button
var val1JSON="<button style\=\"border:none\; background-color\:transparent\; color\:white\; font\-size\:1em\; text\-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop\(\'"+valButton+"\')\">"+symbolLink + "</button> <font color=\""+farbeSchalterON+"\">";
//Den HTML-Code des Buutons noch so ausmaskieren das man ihn in einem JSON unterbingen darf (wegen der " ")
let valJSON = val1JSON.replace(/"/g, '\\"');
//Jetzt könnte man valJSON als Wert in einem JSON setzen
`

In der VIS braucht es jetzt noch ein Script welches auf den Button reagiert. Das habe ich dort hinzugefügt, ggf. ginge auch ein Widget:
`
/* Alexa Einkaufsliste JSON */
function setOnDblClickCustomShop( myvalue ) {
    var Self = this; 
    var objID = myvalue;
    vis.setValue(myvalue,true);
    var2 = "javascript.0.Alexa_Listen.ALEXALists.Einkauf.Refresh"; 
    vis.setValue(var2,true);
    }
`
Das setzt den Datenpunkt `vis.setValue(myvalue,true)` womit das löschen ausgelöst wird,    `javascript.0.Alexa_Listen.ALEXALists.Einkauf.Refresh` dient dazu die Neuerstellung des JSON anzutriggern

**Comment by MiRo1310** [comment]
Hi
Sowas habe ich vorher noch nie gemacht. 
Die Frage ist natürlich, wenn ich nicht alles im Adapter intergiert habe, bzw in die Vis noch Scripte einbauen muss, dann ist es aber für den normalen User zu kompliziert, oder nicht?
Das löschen habe ich ja grundsätzlich mit im Adapter drin.

**Comment by BernhardLinz** [comment]
Jepp, das es für den normalen zu kompliziert sein könnte stimmt.
Maximal ein Widget hinzufügen wäre ok

**Comment by MiRo1310** [comment]
@BernhardLinz 
kannst du mir mal zeigen wie dein Json Code aussieht?

**Comment by BernhardLinz** [comment]
Hier wie ich es gemacht habe:
https://forum.iobroker.net/topic/28254/script-alexa-listen-pflegen-und-anzeigen/364?_=1647505657970

Das JSON sieht so aus:
`[{"Artikel":"Feuchtes Toilettenpapier","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Butter","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Fertigschnitzel","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Remoulade","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Q. Tips","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Rotweincreme","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Klopapier","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Knuspermandelmüsli","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Binden","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Knoblauchsoße","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"},{"Artikel":"Wikingerröhrchen","Delete":"<button style=\"border:none; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.ec25bb9d-00c7-4c6b-adec-d6719455ae9c.#delete')\">❌</button> <font color=\"blue\">"}]`

Wobei nur das Symbol dargestellt wird, die Farbangaben könnten also entfernt werden

**Comment by MiRo1310** [comment]
Ich habe das in den Adapter eingebaut, nur bei mir wird der Button nicht angezeigt, Bzw undefiend angezeigt

**Comment by BernhardLinz** [comment]
Statt des Roten X kann man auch Text etc nehmen, das ist halt ein Unicode-Emoji. `background-color:transparent `und `border:none` noch raus und du solltest einen normalen Button mit Text sehen
Im verlinkten Artikel kannst du die Codezeile finden in der ich den vorgefertigten Button-Code nur nehme und per Replace aufbereite das alle " escaped sind.
Der Button ruft dann die Funktion `setOnDblClickCustomShop` auf welche in VIS hinterlegt sein muss. Ob der dann richtig ist kannst du ja mit den üblichen Webbrowser-Entwicklertools untersuchen.

Vermutlich fehlt ihm die Funktion oder beim Unicodezeichen kopieren passt was nicht, im zweifel als erst einmal nur Text einfügen und Schaltfläche anzeigen lassen wie zuvor beschrieben

**Comment by MiRo1310** [comment]
@BernhardLinz 
Den Button habe ich jetzt soweit drin

**Comment by BernhardLinz** [comment]
Sieht gut aus. 

Das Skript eingebunden heißt aber das immer noch der Code-Schnipsel in der VIS hinterlegt werden muss?
Noch ein Vorschlag: Die Methode löscht ja das Item. Besser würde ich es eigentlich finden wenn man statt dessen den Datenpunkt `completed` nimmt, dann verschiebts sich das Element auf die Erledigt-Liste.

Oder man macht das konfigurierbar - oder eine weitere Spalte dafür.
Was meinst du denn selber?

**Comment by MiRo1310** [comment]
Hi 

ja genau das Script  ist noch in der vis eingebaut. 
probiert habe ich die Funktion mit in die JSON zu packen, ganz am Ende einmal. 
funktioniert aber nicht. 
Dein zweiter Punkt, da habe ich mir gestern schon Gedanken zu gemacht. Das soll man einfach einstellen können ob komplett gelöscht wird oder in die inaktive Liste verschoben werden soll

**Comment by MiRo1310** [comment]
Ich muss mich noch rein arbeiten ein Widget zu bauen, aber erstmal habe ich den Code so angepasst das es funktioniert, in der Readme Datei steht auch der Code der in die Vis eingefügt werden muss.
