### ISSUE TITLE
keine Auswahl einer Liste möglich

### ISSUE THREAD

**Issue by sabbelhardy** [MiRo1310/ioBroker.alexa-shoppinglist#3]
Hallo. 
Ich habe bei der Einrichtung der Instanz von alexa-shoppinglist ein Problem.

Egal, welche Alexa links auswähle,
![image](https://user-images.githubusercontent.com/44242928/210843920-1dadde42-1080-4142-ab9c-700009292cf8.png)

kann ich rechts aus der Liste, weder eine Einkaufsliste oder sonstige Liste auswählen, da dort nichts angezeigt wird.
![image](https://user-images.githubusercontent.com/44242928/210845668-fd75bc62-0a66-4140-a013-a322f8631d72.png)

-	ioBroker läuft als LXC in Proxmox
-	Node V16.18.1
-	NPM 8.19.2
-	JS-Controller 4.0.23
-	Es sind verschiedene Listen in der Alexa vorhanden und aktiv
-	Der Adapter wurde mehrmals gelöscht und wieder installiert
-	Die Instanz bleibt gelb (nicht mit dem Gerät oder Dienst verbunden) und wurde auch öfter neu gestartet
-	Die Instanz von Alexa2.0 wurde ebenfalls neu gestartet

Gruß, Hartmut

**Comment by MiRo1310** [comment]
Perfekt 👌 

Kommt denn irgendwas im log ? 
Hast du das mit dem restart probiert ? 
Eventuell kann auch ein kompletter Restart des iobroker helfen.

**Comment by sabbelhardy** [comment]
> Perfekt 👌
> 
> Kommt denn irgendwas im log ? Hast du das mit dem restart probiert ? Eventuell kann auch ein kompletter Restart des iobroker helfen.

Ja.
![image](https://user-images.githubusercontent.com/44242928/210878481-a0362b31-da45-43e5-a9b1-388334fec1f8.png)
Einen kompletten Restart des ioBroker habe ich auch gemacht. Keine Änderung.

**Comment by sabbelhardy** [comment]
...hat sich alles erledigt.

Man sollte auch mal in der Alexa2.0 die Listen aktivieren. 
Wie so oft, liegt der Fehler vor dem Monitor 🙈

Hab ein schönes Wochenende und Danke für Deinen Adapter.

![image](https://user-images.githubusercontent.com/44242928/210962717-020d484f-bbff-4bff-b8fd-3b5780641a89.png)

**Comment by MiRo1310** [comment]
Perfekt.
