### ISSUE TITLE
Löschen einzelner Pos nicht möglich - mit Warnung im Log

### ISSUE THREAD

**Issue by sabbelhardy** [MiRo1310/ioBroker.alexa-shoppinglist#4]
Hallo,
zuerst einmal - Danke für diesen Adapter. 
Ich konnte soweit alles in der VIS implementieren.

**1. Leider ist kein Löschen mit dem "X" möglich und es erscheint dabei folgende Fehlermeldung im Log:**

> _State "alexa2.0.Lists.SHOPPING_LIST.items.1ee9bc51-2993-4065-b02e-4dce80bc54da.#delete" has no existing object, this might lead to an error in future versions_

- Im VIS-Editor habe ich den Code im "Skript" eingefügt.
- Das sortieren funktioniert jedoch!
- Für den DP "alexa-shoppinglist.0.list_activ" habe ich das Widget "vis-inventwo JSON-Table" verwendet.

**2. Eingabe von neuen Beschreibungen im "add_position"**

Wenn z.B. "Anrufen bei Mercedes Inspektion" eingegeben wird, dann wird lediglich die Großschreibung des 1.Wortes berücksichtigt.
Eingabe von Ziffern ist nicht möglich. z.B. wird "12" in "zwölf" gewandelt.
Öfter werden auch - nicht reproduzierbar - Eingaben mit mehreren Worten abgeschnitten, sodass z.B. nur 2 von 4 Wörtern übernommen werden.

- Das verwendete Widget "materialdesign-input"

Ich hoffe, ich mache dir nicht zu viel Kopfzerbrechen.
Wünsche ein schönes Wochenende
Gruß Hartmut

- ioBroker läuft als LXC in Proxmox
Knoten V16.18.1
NPM 8.19.2
JS-Controller 4.0.23

**Comment by MiRo1310** [comment]
Hallo
**zu 1.** 
das hatte ich am Anfang auch, ich meine es hilft das manuelle löschen aller items in der shopping liste über jeweils #delete
**zu2.**
das Problem ist das die Eingabe erst über die Cloud von Alexa geht und dann alles klein geschrieben zurück kommt. 
Jetzt wird von mir aus schon mal das erste Wort groß geschrieben, ich weiss aber nicht wie man die anderen Wörter herausfiltern kann.
Mit den zahlen genau das gleiche, die werden in der cloud in text gewandelt
Ich habe es vorhin mit "kaufe 12 Gurken" ausprobiert, ja du hast recht, hier wird kaufe weg geschnitten, aber auch dieses passiert nicht in meinem adapter.
Grundsätzlich funktioniert das schon mit mehreren wörtern.

Vielleicht solltest du einfach eine andere Liste nutzen, z.b. todo oder so. Kann sein das das Verhalten da anders ist.

**Comment by sabbelhardy** [comment]
Guten Morgen.
**Zu 1.**
Das mit dem Löschen über den den DP "alexa-shoppinglist.0.delete_activ_list" hatte ich herausgefunden.
Dann kann man über den Umweg in der Alexa-App die items auch wieder in die Liste zurück bringen. Ist natürlich nicht unbedingt ein vorteilhafter Weg.
Es bleibt die Meldung im Log:

> _State__ "alexa2.0.Lists.SHOPPING_LIST.items.1ee9bc51-2993-4065-b02e-4dce80bc54da.#delete" has no existing object, this might lead to an error in future versions

- Liegt es vielleicht an einem veränderten Controller o.ä.?

**Zu 2.**
Danke für die ausführlichen Informationen. 
Mit dem Zustand, dass z.T. nur abgeschnittene Sätze/Worte in der Liste dargestellt werden, könnte ich leben. Dann kommt jedoch wieder Punkt 1. zum Tragen. Man kann die items nicht wieder direkt, sondern nur über o.b. Umweg löschen, um diese wieder neu zu definieren.
- Ich nutze nur die ToDo-Liste bzw. eigene (personenbezogene) Listen in der Alexa-App als Grundlage. Als Shopping-Liste nutze ich Bring!.
![image](https://user-images.githubusercontent.com/44242928/211188474-d584573b-834c-47e9-bfe6-a59acef4fa92.png)

**Comment by MiRo1310** [comment]
Der Fehler kommt aber vom Alexa2 Adapter.
Ich habe damals alle Einträge gelöscht, evtl. den Alexa2 adapter neu starten. 
So das unter den Objekten keine Einträge mehr vorhanden sind. Ich weiss sonst im Moment keinen Rat.

![grafik](https://user-images.githubusercontent.com/68854794/211190400-5bf60cd5-e2a0-4a71-b3c7-74019fadef60.png)

**Comment by sabbelhardy** [comment]
Ich denke ich habe da ein Problem. Bei mir sieht es leider anders aus...
![image](https://user-images.githubusercontent.com/44242928/211191361-724f276a-83c5-49e3-b110-496093a59df0.png)

Ich hatte jetzt alles gelöscht. Die Instanzen und den Adapter,
Dann die Installation noch einmal Benutzerdefiniert mit "https://github.com/MiRo1310/ioBroker.alexa-shoppinglist.git" gemacht und erhalte die gleiche Instanz, wie oben gezeigt.
Was mache ich denn falsch?

**Comment by MiRo1310** [comment]
Die items sind im Alexa2 Adapter und nicht in meinem. 
Alle aus dem alexa2 Adapter löschen und noch mal testen

**Comment by sabbelhardy** [comment]
Es tut mir Leid, dass ich dir die Zeit stehle. Ich kann machen, was ich will.

- Alle items in Alexa2 gelöscht.
- Die Instanzen Deines Adapters gelöscht.
- Adapter gelöscht.
- Adapter neu installiert (jetzt über NPM)
- Alexa2 Adapter neu gestartet

Immer wieder kommt die bereits genannte Meldung
<html>
<body>


ws.0 | 2023-01-08 14:16:55.772 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.69cf0b8d-b2e7-4e81-aebb-6ffae3556c98.#delete" has no existing object, this might lead to an error in future versions
-- | -- | -- | --



</body>
</html>

**Comment by MiRo1310** [comment]
Wenn du den Button #delete in der Liste vom Alexa2 Adapter drückst, kommt dann auch der Fehler?

**Comment by MiRo1310** [comment]
Von welchem Adapter kommt denn der Fehler? 
Was ist ws.0?

**Comment by sabbelhardy** [comment]
> Wenn du den Button #delete in der Liste vom Alexa2 Adapter drückst, kommt dann auch der Fehler?

Nein.
<html>
<body>


alexa2.0 | 2023-01-08 15:48:23.276 | info | Deleting item "tapete aussuchen" from the list [Gisela.
-- | -- | -- | --



</body>
</html>

ws.0 ist:
[https://github.com/ioBroker/ioBroker.web/blob/master/README.md](url)

**Comment by MiRo1310** [comment]
Ok, den habe ich nicht installiert. Habe ich aber testweise mal gemacht. Aber auch da kein Problem.
Ich habe gerade keinen Rat

**Comment by sabbelhardy** [comment]
OK. Danke dir für die Mühe.
Dann muss ich mal schauen, wie ich meine Vorstellungen ohne Adapter umsetze.
Sind denn Node und NPM gleich?

**Comment by MiRo1310** [comment]
ich habe js controller 4.0.23
npm 8.15.0
node 16.17.0
nur habe ich nicht den websocket adapter, sondern den socketio adapter

**Comment by sabbelhardy** [comment]
Ich habe jetzt auch den socketio genommen und den websocket deinstalliert - aber das gleiche Problem beim Löschen behalten.
<html>
<body>


socketio.0 | 2023-01-08 20:24:23.152 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.3a4e6652-1933-4281-b485-26224789480f.#delete" has no existing object, this might lead to an error in future versions
-- | -- | -- | --



</body>
</html>

**Comment by MiRo1310** [comment]
Welche Version vom Alexa2 Adapter hast du ?

**Comment by MiRo1310** [comment]
Der Fehler sagt eigentlich aus das der Datenpunkt nicht vorhanden ist, welcher gelöscht werden soll. Du könntest mal schauen ob dieser wirklich nicht existiert.
Vergleiche einfach die ids der JSon Liste mit den ids der items in alexa2.0.Lists....

**Comment by sabbelhardy** [comment]
Die Version vom Adapter: **alexa2.0  v3.23.2**

z.B. möchte ich löschen

- Die ID aus Deinem DP "list_aktiv" - "id": "3a4e6652-1933-4281-b485-26224789480f"
`{
    "name": "Test",
    "time": "1/8/2023, 8:23:02 PM",
    "id": "3a4e6652-1933-4281-b485-26224789480f",
    "pos": 2,
    "buttonmove": "<button style=\"border:none; cursor:pointer; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.3a4e6652-1933-4281-b485-26224789480f.completed,true')\">↪</button> <font color=\"green\">",
    "buttondelete": "<button style=\"border:none; cursor:pointer; background-color:transparent; color:white; font-size:1em; text-align:center\" value=\"toggle\" onclick=\"setOnDblClickCustomShop('alexa2.0.Lists.SHOPPING_LIST.items.3a4e6652-1933-4281-b485-26224789480f.#delete,true')\">❌</button> <font color=\"green\">"
  }` 

- Die aus DP der entsprechenden List - JSON (List as json) - "id": "3a4e6652-1933-4281-b485-26224789480f"
`{
    "completed": false,
    "createdDateTime": 1673205782034,
    "customerId": "A3I6NJMCU6G8MG",
    "id": "3a4e6652-1933-4281-b485-26224789480f",
    "listId": "2b70afb1-f96c-4b93-be63-c401b15dd3eb",
    "shoppingListItem": false,
    "updatedDateTime": 1673205782034,
    "value": "test",
    "version": 1
  },`

Liegt es möglicherweise doch am Widget "vis-inventwo JSON-Table"?

**Comment by sabbelhardy** [comment]
Am Widget schein es nicht zu liegen. Habe eben noch einmal ein basic-table ausprobiert

**Comment by MiRo1310** [comment]
Hi ich habe das Problem gefunden. Ich werde mich nachher dran setzen es zu beheben

**Comment by sabbelhardy** [comment]
Ohh - das freut mich.
War schon am verzweifeln.

**Comment by MiRo1310** [comment]
So der Fehler ist behoben, du kannst noch einmal direkt von Github installieren

**Comment by sabbelhardy** [comment]
Perfekt. Vielen Dank.
