### ISSUE TITLE
buttonmove aus json funktioniert nicht

### ISSUE THREAD

**Issue by jomahol** [MiRo1310/ioBroker.alexa-shoppinglist#81]
Hallo MiRo1310, ich experimentiere gerade mit deinem Adapter  (Version 0.1.5).
Leider funktioniert der Button "buttonmove" aus der json Datei hier nicht bzw. erzeugt einen Fehler im alexa2 Adapter (v3.26.5).
Für die Visualisierung benutze ich vis-2.0 (v2.9.32) mit dem Widget "Basic Table"

Das Script ist installiert. Der Button "buttondelete" funktioniert entsprechend wie er soll.
Irgendeine Idee wo das Problem liegen könnte?

Ansonsten... alles perfekt 👍 vielen Dank dafür.

dazugehörige Meldungen aus dem log:
2024-07-31 12:14:56.538 - info: web.0 (83952) State value to set for "alexa2.0.Lists.SHOPPING_LIST.items.3544ff6b-dfaf-4693-8f40-17a24bdcf0f8.completed" has to be type "boolean" but received type "string"
--
2024-07-31 12:14:56.543 - error: alexa2.0 (113319) Datatype "string" for Lists.SHOPPING_LIST.items.3544ff6b-dfaf-4693-8f40-17a24bdcf0f8.completed differs from expected "boolean", ignore state change! Please write correct datatype

mfg joma

Betriebssystem: linux
Architektur: x64
Modell: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
RAM: 5.6 GB
Node.js: v18.20.4
NPM: 10.7.0

**Comment by MiRo1310** [comment]
Muss ich mir nächste Woche mal anschauen.

**Comment by MiRo1310** [comment]
Das sollte den Fehler fixen 
```
function setOnDblClickCustomShop( myvalue) {
    let id = myvalue.slice(0,myvalue.indexOf(","));
    let val = myvalue.slice(myvalue.indexOf(",")+1, myvalue.length);
    if (val=== "true"){
      vis.setValue(id,true);
      return
    }
    vis.setValue(id,false);
  }
```

**Comment by jomahol** [comment]
Prima, mit der Änderung funktioniert's jetzt.... vielen Dank. :-)
